name: deploy raillo raillo-frontend

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Use Node.js version 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x # μµμ‹  Next.js νΈν™

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install Dependencies (pnpm)
        run: pnpm install

      - name: Patch swc dependencies (for Next.js)
        run: pnpm exec next --help > /dev/null

      - name: Build & Export
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_KAKAO_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_KAKAO_MAPS_API_KEY }}
          NODE_ENV: production
        run: |
          pnpm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 rm s3://raillo-frontend --recursive
          aws s3 cp --recursive --region ap-northeast-2 ./out s3://raillo-frontend

      - name: Clear Cache to Cloudfront
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws cloudfront create-invalidation --distribution-id E3EVY7JHHX1RQX --paths "/*"
